*** Settings ***
Documentation  Este arquivo contém as variáveis de massa de dados para o sistema de vendas (https://www.saucedemo.com/).

*** Variables ***
&{DIC_POSICOES}
...  primeiro=1
...  segundo=2
...  terceiro=3
...  quarto=4
...  quinto=5
...  sexto=6

&{DIC_PRODUTOS_ADICIONADOS}
...  primeiro=
...  segundo=
...  terceiro=
...  quarto=
...  quinto=
...  sexto=

@{LIST_POSICAO_PRODUTOS_ADICIONADOS}