*** Variables ***
${INVENTORY_LINK_CARRINHO}  //a[@data-test="shopping-cart-link"]

${INVENTORY_DIV_INVENTARIO_ITEM}  //div[@data-test="inventory-item"]

${INVENTORY_LBL_ITEM_NOME}  //div[@data-test="inventory-item-name"]

${INVENTORY_BTN_ADICIONAR_CARRINHO}  //button[contains(text(), 'Add to cart')]

#${INVENTORY_BTN_ADICIONAR_CARRINHO}  //button[@data-test="add-to-cart-{text}"]

${INVENTORY_BTN_REMOVER_CARRINHO}  //button[@data-test="remove-{text}"]