*** Variables ***
${ACCOUNT_HISTORY_TITLE}  //h1[contains(text(), 'Account History - ')]

${TITLE_TABLE_RECENT_TRANSACTIONS}  //b[text()="10 Most Recent Transactions"]

${TABLE_RECENT_TRANSACTIONS}  //div[@id="recent"]/table/tbody

${TABLE_BALANCE_DETAIL}  //td[contains(text(), 'Available balance')]/following-sibling::td

${TITLE_TABLE_RECENT_TRANSACTIONS}  //b[text()="10 Most Recent Transactions"]

${TABLE_RECENT_TRANSACTIONS}  //div[@id="recent"]/table/tbody